const cursors = [
    {
        category:"Featured",
        data:[
            {
                id:"light-darkblue",
                name:"Blue",
                image:"light-darkblue.png"
            },
            {
                id:"pink-gradient",
                name:"Pink",
                image:"pink-gradient.png"
            },
            {
                id:"green-graident",
                name:"Green",
                image:"green-graident.png"
            },
            {
                id:"violet-red",
                name:"Hue",
                image:"violet-red.png"
            },
            {
                id:"rainbow",
                name:"Rainbow",
                image:"rainbow.png"
            },
            {
                id:"balloon",
                name:"Balloon",
                image:"balloon.png"
            },
            {
                id:"hallo",
                name:"Halloween",
                image:"hallo.png"
            },
            {
                id:"acorn",
                name:"Acorn",
                image:"acorn.png"
            },
            {
                id:"stripe",
                name:"Stripe",
                image:"stripe.png"
            },
            {
                id:"pokeball",
                name:"Pokeball",
                image:"pokeball.png"
            },
            {
                id:"vader",
                name:"Darth Vader",
                image:"vader.png"
            },
            {
                id:"saber",
                name:"Lightsaber",
                image:"saber.png"
            }
        ]
    },
    {
        category:"Colors",
        data:[
            {
                id:"red",
                name:"Red",
                image:"red.png"
            },
            {
                id:"orange",
                name:"Orange",
                image:"orange.png"
            },
            {
                id:"yellow",
                name:"Yellow",
                image:"yellow.png"
            },
            {
                id:"lime",
                name:"lime",
                image:"lime.png"
            },
            {
                id:"green",
                name:"Green",
                image:"green.png"
            },
            {
                id:"teal",
                name:"Teal",
                image:"teal.png"
            },
            {
                id:"light_blue",
                name:"Light Blue",
                image:"light_blue.png"
            },
            {
                id:"blue",
                name:"Blue",
                image:"blue.png"
            },
            {
                id:"indigo",
                name:"Indigo",
                image:"indigo.png"
            },
            {
                id:"purple",
                name:"Purple",
                image:"purple.png"
            },
            {
                id:"pink",
                name:"Pink",
                image:"pink.png"
            },
            {
                id:"magenta",
                name:"Magenta",
                image:"magenta.png"
            }
        ]
    },
    {
        category:"Animals",
        data:[
            {
                id:"fish",
                name:"Fish",
                image:"fish.png"
            },
            {
                id:"cat",
                name:"Cat",
                image:"cat.png"
            },
            {
                id:"pug",
                name:"Pug",
                image:"pug.png"
            },
            {
                id:"rabbit",
                name:"Rabbit",
                image:"rabbit.png"
            },
            {
                id:"bird",
                name:"Bird",
                image:"bird.png"
            },
            {
                id:"pig",
                name:"Pig",
                image:"pig.png"
            },
            {
                id:"beetle",
                name:"Beetle",
                image:"beetle.png"
            },
            {
                id:"kangaroo",
                name:"Kangaroo",
                image:"kangaroo.png"
            },
        ]
    },
    {
        category:"Overwatch",
        data:[
            {
                id:"tracer",
                name:"Tracer",
                image:"tracer.png"
            },
            {
                id:"mcree",
                name:"Mcree",
                image:"mcree.png"
            },
            {
                id:"odette",
                name:"Odette",
                image:"odette.png"
            },
            {
                id:"widow",
                name:"Widow",
                image:"widow.png"
            },
            {
                id:"dva",
                name:"D.va",
                image:"dva.png"
            },
            {
                id:"mech",
                name:"Mech",
                image:"mech.png"
            },
            {
                id:"genjiUlt",
                name:"Blade",
                image:"genjiUlt.png"
            },
            {
                id:"genji",
                name:"Genji",
                image:"genji.png"
            },
        ]
    },
    {
        category:"Emoji",
        data:[
            {
                id:"joy",
                name:"Joy",
                image:"joy.png"
            },
            {
                id:"smile",
                name:"Happy",
                image:"smile.png"
            },
            {
                id:"smileSweat",
                name:"Smile",
                image:"smileSweat.png"
            },
            {
                id:"silly",
                name:"Silly",
                image:"silly.png"
            },
            {
                id:"heartEyes",
                name:"Hearts",
                image:"heartEyes.png"
            },
            {
                id:"kiss",
                name:"Kissing",
                image:"kiss.png"
            },
            {
                id:"smirk",
                name:"Smirking",
                image:"smirk.png"
            },
            {
                id:"thinking",
                name:"Thinking",
                image:"thinking.png"
            },
            {
                id:"sad",
                name:"Sad",
                image:"sad.png"
            },
            {
                id:"fear",
                name:"Fear",
                image:"fear.png"
            },
            {
                id:"angry",
                name:"Angry",
                image:"angry.png"
            },
            {
                id:"glasses",
                name:"Glasses",
                image:"glasses.png"
            },
        ]
    }
]

export default cursors

                                    
                                        
                        